const genreKanji = {
  Fantasy: "幻想",
  "Science Fiction": "科幻",
  Mystery: "謎",
  Romance: "恋愛",
  Horror: "恐怖",
  "Historical Fiction": "歴史",
  Thriller: "緊張",
  Adventure: "冒険",
  Comedy: "喜劇",
  "Slice of Life": "日常",
  Drama: "劇",
  Action: "動作",
  Supernatural: "超常",
  Mythology: "神話",
  Detective: "探偵",
  Psychological: "心理",
  Cyberpunk: "電脳",
  Steampunk: "歯車",
  Dystopian: "暗黒",
  Utopian: "理想",
  Sports: "運動",
  "Martial Arts": "武術",
  Military: "軍事",
  Philosophical: "哲学",
  Political: "政治",
  Tragedy: "悲劇",
  Survival: "生存",
  Crime: "犯罪",
  "Magical Realism": "魔幻",
  Espionage: "諜報",
  "Post-Apocalyptic": "終末",
  "Coming of Age": "成長",
};

export default genreKanji;
